services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cardb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  app:
    image: car-rent
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cardb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: dev
      SENDGRID_ENABLED: "false"
    depends_on:
      - db
